check for detectorbank.py in run_full_tests

diff --git a/run_full_tests b/run_full_tests
--- a/run_full_tests
+++ b/run_full_tests
@@ -12,8 +12,12 @@ else
     detBankDir="$DETBANKDIR"
 fi
 
-echo $pythonVersion
-echo $detBankDir
+if [ ! -e "$DETBANKDIR/detectorbank.py" ]; then
+    echo "detectorbank.py not found in $detBankDir"
+    echo "Please install DetectorBank or set PYTHON_VERSION and/or DETBANKDIR appropriately"
+    echo "See https://github.com/keziah55/DetectorBank for installation instructions"
+    exit 1
+fi
 
 export PYTHONPATH=$detBankDir:$PYTHONPATH
 
